In [4]:
# Importing relevant packages and establishing the Exadata connection

import sqlalchemy
import pandas as pd
import numpy as np
import getpass

password=getpass.getpass("Enter your password:")
engine = sqlalchemy.create_engine("oracle+cx_oracle://anantk[an_ct_ws38]:%s@exa_gbtukprdd_an" %(password))


Enter your password:········


In [15]:
# trans = pd.read_sql("SELECT  distinct transaction_fid,dense_rank()over() as tpnb_code FROM AK_REP_BSK_PROD_5 a" , engine )
# 
trans_exp = pd.read_sql("SELECT  TRANSACTION_FID,NS_CODE FROM AK_REP_BSK_PROD_64 a where channel_flag = 2" , engine )
# trans_exp
# X = trans_exp
# trans_exp['value'] = 1
# Z = X.to_sparse()
# from scipy.sparse import csr_matrix
# S = csr_matrix(Z)
# D = pd.S
# Y = X.pivot(index='transaction_fid', columns='tpnb_code', values = 'value')
# Y = trans_exp.pivot_table(values='value', index='transaction_fid', columns='ns_code', aggfunc='sum').to_sparse()
# Y = trans_exp.groupby(['transaction_fid','ns_code'])['value'].max().unstack()
# df.groupby(['newidx', 'Code'])['val'].max().unstack()
# df.pivot_table(values='val', index='newidx', columns='Code', aggfunc='max')

# Y.fillna(0)
# Y
# Z=Y.copy(deep=True)
# # A = Z.reset_index()
# # A.set_index('transaction_fid',inplace=True)
# # D.iloc[A[0] == 1,0]


B = pd.DataFrame()
for i in D.columns:
    Y = pd.DataFrame()
    free = []
    for z in D.columns:
        data = D.loc[D[i] == 1, z].sum()
        free.append(data)
    Y = pd.DataFrame(np.array(free)).transpose()
    B = pd.concat([B,Y])       

# B.columns = D.columns 
# B.set_index('ns_code',inplace = True)
# B.reindex()

# B.to_csv('/nfs/science/shared/ipythonNotebooks/anantk/B.csv')


No handlers could be found for logger "sqlalchemy.pool.QueuePool"


KeyboardInterrupt: 

In [289]:
pd.concat([pd.DataFrame(Z),pd.DataFrame(Y)])

0   1   2   3   4   5   6   7   8   9  ...  90  91  92  93  94  95  96  97  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   

   98  99  
0   0   0  
0   0   0  

[2 rows x 100 columns]

In [36]:
import subprocess
import pandas as pd
import os
from urllib import quote_plus as urlquote

proxy = "anantk[an_ct_ws38]/Sushant123@exa_gbtukprdd_an"

cmd_str =   "xdatadump userid='" + str(proxy) \
                + "' sqlstmt='SELECT  TRANSACTION_FID,NS_CODE,1 as value FROM AK_REP_BSK_PROD_64 a where channel_flag = 2" \
                +  "' delimiter=^ header=y > exp_trans.csv"
print cmd_str
subprocess.call(cmd_str, cwd='./', shell=True)

xdatadump userid='anantk[an_ct_ws38]/Sushant123@exa_gbtukprdd_an' sqlstmt='SELECT  TRANSACTION_FID,NS_CODE,1 as value FROM AK_REP_BSK_PROD_64 a where channel_flag = 2' delimiter=^ header=y > exp_trans.csv


0

In [20]:
# df = pd.read_csv('exp_trans.csv',header=0, delimiter="^").groupby(['TRANSACTION_FID','NS_CODE'])['VALUE'].max().unstack()

# D = df.fillna(0).to_sparse()

# B = pd.DataFrame()
for i in range(260,265):
    Y = pd.DataFrame()
    free = []
    for z in df.columns:
        data = df.groupby([df[i] == 1])[z].sum()
        free.append(data[1])
    Y = pd.DataFrame(np.array(free)).transpose()
    B = pd.concat([B,Y])       

# df

In [59]:
# x =  np.array([0,1,1])

# print x

# y = np.array([x]).T
  
# print "\n",x*y


b = np.array([[1, 1, 2], [3, 4, 5],[6,7,8]])  

print "\n",b

# print "\n",np.sum((x*y)*b)
c = np.diag(b)

print c 

d = np.sum(c)

print d 

a =pd.DataFrame()
for i in range(3):
    q = []
    y = pd.DataFrame()
    for j in range(3):
        print b[i,j],d,c[i],c[j]
        x = (b[i,j]*d)/(c[i]*c[j]).astype(float)
        q.append(x)
        y = pd.DataFrame(q).transpose()
    a = pd.concat([a,y])

s = a.as_matrix()
s




[[1 1 2]
 [3 4 5]
 [6 7 8]]
[1 4 8]
13
1 13 1 1
1 13 1 4
2 13 1 8
3 13 4 1
4 13 4 4
5 13 4 8
6 13 8 1
7 13 8 4
8 13 8 8


array([[ 13.     ,   3.25   ,   3.25   ],
       [  9.75   ,   3.25   ,   2.03125],
       [  9.75   ,   2.84375,   1.625  ]])

In [73]:
# c.T
# y = np.array([c]).T
# print "\n",c*y
g = np.matrix(b)
print "\n",g
print "\n",(g*d)/(c*c.T)

q =[]
for i,j in enumerate(g):
    print i
    print j
#     x = (g[i,j]*d)/(c[i]*c[j]).astype(float)
#     q.append(x)

# q


[[1 1 2]
 [3 4 5]
 [6 7 8]]

[[13  0  0]
 [39  3  1]
 [78  5  1]]
0
[[1 1 2]]
1
[[3 4 5]]
2
[[6 7 8]]


In [74]:
ns_2way = pd.read_csv("ns.csv")
prod = pd.read_csv("top_prods_ns.csv")

print ns_2way.shape
print ns_2way.head()
print prod.head()

Asso_matrix = ns_2way.ix[:,1:973].as_matrix()

print Asso_matrix.shape
print Asso_matrix


(972, 974)
        Unnamed: 0  1 Litre Sauces  10mth Meal Jar  4-6mth Cereal  \
0   1 Litre Sauces               1               0              0   
1   10mth Meal Jar               0               8              0   
2    4-6mth Cereal               0               0              8   
3   4-6mth Dessert               0               0              0   
4  4-6mth Meal Jar               0               0              1   

   4-6mth Dessert  4-6mth Meal Jar  7-9mth Cereal  7-9mth Dessert  \
0               0                0              0               0   
1               0                0              0               0   
2               0                1              1               0   
3               8                2              0               1   
4               2             1063              0               0   

   7-9mth Meal Jar  ADULT SNACKING CHEESE      ...       Sherry  Shoe Laces  \
0                0                      0      ...            0           0   
1

In [78]:
b = Asso_matrix

c = np.diag(Asso_matrix)

# print c 

d = np.sum(c)

print d 

a =pd.DataFrame()
for i in range(972):
    q = []
    y = pd.DataFrame()
    for j in range(972):
#         print b[i,j],d,c[i],c[j]
        x = (b[i,j]*d)/(c[i]*c[j]).astype(float)
        q.append(x)
        y = pd.DataFrame(q).transpose()
    a = pd.concat([a,y])

s = a.as_matrix()
s
a

18191922


array([[  1.81919220e+07,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.27399025e+06,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   2.27399025e+06, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          3.37888596e+03,   2.92324157e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.92324157e+00,   2.28097574e+02,   1.52914575e+01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.52914575e+01,   1.01630849e+05]])

In [79]:
a

0             1             2             3             4    \
0   18191922.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  2.273990e+06  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  2.273990e+06  0.000000e+00   2139.219426   
0          0.0  0.000000e+00  0.000000e+00  2.273990e+06   4278.438852   
0          0.0  0.000000e+00  2.139219e+03  4.278439e+03  17113.755409   
0          0.0  0.000000e+00  4.547980e+05  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  4.547980e+05      0.000000   
0          0.0  3.799482e+03  0.000000e+00  1.899741e+03   1229.559704   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      8.662561   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      4.324932   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00     11.954286   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      5.293460   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      2.160419   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      2.550675   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      2.153757   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00     10.198901   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      1.963393   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      7.947318   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      9.762553   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      8.779887   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
..         ...           ...           ...           ...           ...   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      1.183197   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      3.223537   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      8.307648   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      8.287533   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      1.559159   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      2.104495   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      6.486168   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      3.099756   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      3.406457   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00     29.379838   
0          0.0  0.000000e+00  0.000000e+00  0.000000e+00      0.000000   
0          0.0 